# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interpolacao.ui'
#
# Created: Sun Jun  5 17:27:41 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_interpolacaoPrincipal(object):
    def setupUi(self, interpolacaoPrincipal):
        interpolacaoPrincipal.setObjectName(_fromUtf8("interpolacaoPrincipal"))
        interpolacaoPrincipal.resize(810, 536)
        self.centralwidget = QtGui.QWidget(interpolacaoPrincipal)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 281, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.txtX = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.txtX.setObjectName(_fromUtf8("txtX"))
        self.horizontalLayout.addWidget(self.txtX)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(280, 0, 521, 51))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtY = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.txtY.setObjectName(_fromUtf8("txtY"))
        self.horizontalLayout_2.addWidget(self.txtY)
        self.btnAleatorios = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        self.btnAleatorios.setFont(font)
        self.btnAleatorios.setObjectName(_fromUtf8("btnAleatorios"))
        self.horizontalLayout_2.addWidget(self.btnAleatorios)
        self.txtQuantidade = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.txtQuantidade.setObjectName(_fromUtf8("txtQuantidade"))
        self.horizontalLayout_2.addWidget(self.txtQuantidade)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(3, 49, 801, 51))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnGrafico = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(10)
        self.btnGrafico.setFont(font)
        self.btnGrafico.setObjectName(_fromUtf8("btnGrafico"))
        self.horizontalLayout_3.addWidget(self.btnGrafico)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.txtPrecisao = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.txtPrecisao.setObjectName(_fromUtf8("txtPrecisao"))
        self.horizontalLayout_3.addWidget(self.txtPrecisao)
        self.cmbMetodo = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.cmbMetodo.setObjectName(_fromUtf8("cmbMetodo"))
        self.cmbMetodo.addItem(_fromUtf8(""))
        self.cmbMetodo.addItem(_fromUtf8(""))
        self.cmbMetodo.addItem(_fromUtf8(""))
        self.cmbMetodo.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cmbMetodo)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.txtPonto = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.txtPonto.setEnabled(False)
        self.txtPonto.setObjectName(_fromUtf8("txtPonto"))
        self.horizontalLayout_3.addWidget(self.txtPonto)
        self.btnCalcular = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        self.btnCalcular.setFont(font)
        self.btnCalcular.setObjectName(_fromUtf8("btnCalcular"))
        self.horizontalLayout_3.addWidget(self.btnCalcular)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 801, 381))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.txtResultado = QtGui.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(14)
        self.txtResultado.setFont(font)
        self.txtResultado.setObjectName(_fromUtf8("txtResultado"))
        self.verticalLayout.addWidget(self.txtResultado)
        interpolacaoPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(interpolacaoPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        interpolacaoPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(interpolacaoPrincipal)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        interpolacaoPrincipal.setStatusBar(self.statusbar)
        self.actionSalvarComo = QtGui.QAction(interpolacaoPrincipal)
        self.actionSalvarComo.setObjectName(_fromUtf8("actionSalvarComo"))
        self.menuArquivo.addAction(self.actionSalvarComo)
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(interpolacaoPrincipal)
        QtCore.QMetaObject.connectSlotsByName(interpolacaoPrincipal)

    def retranslateUi(self, interpolacaoPrincipal):
        interpolacaoPrincipal.setWindowTitle(_translate("interpolacaoPrincipal", "Interpolação", None))
        self.label.setText(_translate("interpolacaoPrincipal", "X", None))
        self.txtX.setToolTip(_translate("interpolacaoPrincipal", "Valores de X separados por espaço", None))
        self.txtX.setText(_translate("interpolacaoPrincipal", "1 2 4 5 7", None))
        self.label_2.setText(_translate("interpolacaoPrincipal", "Y", None))
        self.txtY.setToolTip(_translate("interpolacaoPrincipal", "Valores de Y separados por espaço", None))
        self.txtY.setText(_translate("interpolacaoPrincipal", "52 5 -5 -40 10", None))
        self.btnAleatorios.setText(_translate("interpolacaoPrincipal", "Gerar Pontos Aleatórios", None))
        self.txtQuantidade.setText(_translate("interpolacaoPrincipal", "3", None))
        self.btnGrafico.setText(_translate("interpolacaoPrincipal", "Ver gráfico", None))
        self.label_3.setText(_translate("interpolacaoPrincipal", "Precisão", None))
        self.txtPrecisao.setToolTip(_translate("interpolacaoPrincipal", "Número de casas decimais", None))
        self.txtPrecisao.setText(_translate("interpolacaoPrincipal", "4", None))
        self.cmbMetodo.setItemText(0, _translate("interpolacaoPrincipal", "Mínimos Quadrados", None))
        self.cmbMetodo.setItemText(1, _translate("interpolacaoPrincipal", "Splines Lineares", None))
        self.cmbMetodo.setItemText(2, _translate("interpolacaoPrincipal", "Interpolação de Lagrange", None))
        self.cmbMetodo.setItemText(3, _translate("interpolacaoPrincipal", "Diferenças divididas de Newton", None))
        self.label_4.setText(_translate("interpolacaoPrincipal", "Ponto", None))
        self.txtPonto.setToolTip(_translate("interpolacaoPrincipal", "Ponto a ser interpolado", None))
        self.txtPonto.setText(_translate("interpolacaoPrincipal", "3", None))
        self.btnCalcular.setText(_translate("interpolacaoPrincipal", "Calcular", None))
        self.menuArquivo.setTitle(_translate("interpolacaoPrincipal", "Arquivo", None))
        self.actionSalvarComo.setText(_translate("interpolacaoPrincipal", "Salvar Como", None))

